##BUCLE while
## se encarga de ejecutar una misma accion
while True:
    print("hola")
##bucle for
##nos permite iterar sobre una variable compleja 
for numero in range (1,11):
print(numero)
##int tipo de texto a un dato de tipo numerico real o entero 
##input metodo de python que pide un dato por consola al usuario 
while True:
    numero=int(input("ingresa el num ganador"))
    if numero==10:
        print ("ganaste el premio")
        condicion=False
    else:
        print("sientate chato ese el numero")
        